dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
dependencies:
  - OpenZeppelin/openzeppelin-contracts@5.0.0
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@5.0.0"